config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :accounts do
  resources :savings
  resources :currents
  end

  resources :merchants
  resources :savings
  resources :currents
  resources :cards
  resources :investments
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get '/check_user', to: 'home#ajax', as: 'checkuser'
  get '/transactions', to: 'savings#index', as: 'transactions'
  get '/pay', to: 'currents#new', as: 'pay'
  get '/success', to: 'currents#success', as: 'success'

  devise_scope :user do
  get '/users/sign_out' => 'devise/sessions#destroy'
  end

  root 'home#index'
end

app/models/saving.rb
class Saving < ApplicationRecord
      belongs_to :account, optional: true
end

app/controllers/savings_controller.rb
class SavingsController < ApplicationController
  before_action :set_saving, only: [:show, :edit, :update, :destroy]
  skip_before_action :verify_authenticity_token


  # GET /savings
  # GET /savings.json
  def index
      @savings = Saving.where(account_id: params[:account_id] )

      respond_to do |format|
        format.html
        format.json { render :json => @savings }
    end

  end

  # GET /savings/1
  # GET /savings/1.json
  def show
      @latestsavings = Saving.all.last
    respond_to do |format|
        format.html
        format.json { render :json => @latestsavings }
    end

  end

  # GET /savings/new
  def new
    @saving = Saving.new
  end

  # GET /savings/1/edit
  def edit
  end

  # POST /savings
  # POST /savings.json
  def create


    @saving = Saving.new(saving_params)

    respond_to do |format|
      if @saving.save
        format.html { redirect_to @saving, notice: 'Saving was successfully created.' }
        format.json { render :show, status: :created, location: @saving }
      else
        format.html { render :new }
        format.json { render json: @saving.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /savings/1
  # PATCH/PUT /savings/1.json
  def update
    respond_to do |format|
      if @saving.update(saving_params)
        format.html { redirect_to @saving, notice: 'Saving was successfully updated.' }
        format.json { render :show, status: :ok, location: @saving }
      else
        format.html { render :edit }
        format.json { render json: @saving.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /savings/1
  # DELETE /savings/1.json
  def destroy
    @saving.destroy
    respond_to do |format|
      format.html { redirect_to savings_url, notice: 'Saving was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_saving
      @saving = Saving.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def saving_params
      params.require(:saving).permit(:amount, :balance, :sort, :operation, :date, :created_at, :updated_at, :account_id)
    end
end

app/helpers/savings_helper.rb
module SavingsHelper
end

app/views/savings/_form.html.erb
<%= form_with(model: saving, local: true) do |form| %>
  <% if saving.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(saving.errors.count, "error") %> prohibited this saving from being saved:</h2>

      <ul>
      <% saving.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :amount %>
    <%= form.text_field :amount %>
  </div>

  <div class="field">
    <%= form.label :balance %>
    <%= form.text_field :balance %>
  </div>

  <div class="field">
    <%= form.label :type %>
    <%= form.text_field :type %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/savings/edit.html.erb
<h1>Editing Saving</h1>

<%= render 'form', saving: @saving %>

<%= link_to 'Show', @saving %> |
<%= link_to 'Back', savings_path %>

app/views/savings/index.html.erb
<%= javascript_pack_tag 'hello_react' %>

app/views/savings/new.html.erb
<h1>New Saving</h1>

<%= render 'form', saving: @saving %>

<%= link_to 'Back', savings_path %>

app/views/savings/show.html.erb
<h1>SAAAVE</h1>
savings # show