config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :accounts do
  resources :savings
  resources :currents
  end

  resources :merchants
  resources :savings
  resources :currents
  resources :cards
  resources :investments
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get '/check_user', to: 'home#ajax', as: 'checkuser'
  get '/transactions', to: 'savings#index', as: 'transactions'
  get '/pay', to: 'currents#new', as: 'pay'
  get '/success', to: 'currents#success', as: 'success'

  devise_scope :user do
  get '/users/sign_out' => 'devise/sessions#destroy'
  end

  root 'home#index'
end

app/models/current.rb
class Current < ApplicationRecord
    belongs_to :account, optional: true
end

app/controllers/currents_controller.rb
class CurrentsController < ApplicationController
  before_action :set_current, only: [:show, :edit, :update, :destroy]
  skip_before_action :verify_authenticity_token

def success
end

  # GET /currents
  # GET /currents.json
  def index
    @current = Current.where(account_id: params[:account_id] )

      respond_to do |format|
        format.html
        format.json { render :json => @current }
  end
end

  # GET /currents/1
  # GET /currents/1.json
  def show
        @latestcurrent = Current.all.last

        respond_to do |format|
        format.html
        format.json { render :json => @latestcurrent }
    end

  end

  # GET /currents/new
  def new
    @current = Current.new
  end

  # GET /currents/1/edit
  def edit
  end

  # POST /currents
  # POST /currents.json
  def create



    @current = Current.new(current_params)

    respond_to do |format|
      if @current.save
        format.html { redirect_to @current, notice: 'Current was successfully created.' }
        format.json { render :show, status: :created, location: @current }
      else
        format.html { render :new }
        format.json { render json: @current.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /currents/1
  # PATCH/PUT /currents/1.json
  def update
    respond_to do |format|
      if @current.update(current_params)
        format.html { redirect_to @current, notice: 'Current was successfully updated.' }
        format.json { render :show, status: :ok, location: @current }
      else
        format.html { render :edit }
        format.json { render json: @current.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /currents/1
  # DELETE /currents/1.json
  def destroy
    @current.destroy
    respond_to do |format|
      format.html { redirect_to currents_url, notice: 'Current was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_current
      @current = Current.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def current_params
      params.require(:current).permit(:amount, :balance, :sort, :operation, :date, :account_id, :created_at, :updated_at)
    end
end

app/helpers/currents_helper.rb
module CurrentsHelper
end

app/views/currents/_form.html.erb
<%= form_with(model: current, local: true) do |form| %>
  <% if current.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(current.errors.count, "error") %> prohibited this current from being saved:</h2>

      <ul>
      <% current.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :amount %>
    <%= form.text_field :amount %>
  </div>

  <div class="field">
    <%= form.label :balance %>
    <%= form.text_field :balance %>
  </div>

  <div class="field">
    <%= form.label :app %>
    <%= form.check_box :app %>
  </div>

  <div class="field">
    <%= form.label :type %>
    <%= form.text_field :type %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/currents/edit.html.erb
<h1>Editing Current</h1>

<%= render 'form', current: @current %>

<%= link_to 'Show', @current %> |
<%= link_to 'Back', currents_path %>

app/views/currents/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Currents</h1>

<table>
  <thead>
    <tr>
      <th>Amount</th>
      <th>Balance</th>
      <th>App</th>
      <th>Type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @currents.each do |current| %>
      <tr>
        <td><%= current.amount %></td>
        <td><%= current.balance %></td>
        <td><%= current.sort %></td>
        <td><%= link_to 'Show', current %></td>
        <td><%= link_to 'Edit', edit_current_path(current) %></td>
        <td><%= link_to 'Destroy', current, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>


<%= link_to 'New Current', new_current_path %>

app/views/currents/new.html.erb
<%= javascript_pack_tag 'hello_react' %>

app/views/currents/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Amount:</strong>
  <%= @current.amount %>
</p>

<p>
  <strong>Balance:</strong>
  <%= @current.balance %>
</p>

<p>
  <strong>App:</strong>
  <%= @current.app %>
</p>

<p>
  <strong>Type:</strong>
  <%= @current.type %>
</p>

<%= link_to 'Edit', edit_current_path(@current) %> |
<%= link_to 'Back', currents_path %>

app/views/currents/success.html.erb
<%= javascript_pack_tag 'hello_react' %>