config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :accounts do
  resources :savings
  resources :currents
  end

  resources :merchants
  resources :savings
  resources :currents
  resources :cards
  resources :investments
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get '/check_user', to: 'home#ajax', as: 'checkuser'
  get '/transactions', to: 'savings#index', as: 'transactions'
  get '/pay', to: 'currents#new', as: 'pay'
  get '/success', to: 'currents#success', as: 'success'

  devise_scope :user do
  get '/users/sign_out' => 'devise/sessions#destroy'
  end

  root 'home#index'
end

app/models/account.rb
class Account < ApplicationRecord
    belongs_to :user, optional: true
    has_many :currents
    has_many :savings
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :set_account, only: [:show, :edit, :update, :destroy]
  skip_before_action :verify_authenticity_token

  def invest
    @accounts = Account.where(user_id: current_user.id)
    @investments = Investment.where(account_id: @accounts.ids)

    respond_to do |format|
        format.html
        format.json { render :json => {:accounts => @accounts,
                                        :investments => @investments } }
      end
  end

  # GET /accounts
  # GET /accounts.json
  def index
    @accounts = Account.all
  end

  # GET /accounts/1
  # GET /accounts/1.json
  def show

  end

  # GET /accounts/new
  def new
    @account = Account.new
  end

  # GET /accounts/1/edit
  def edit
  end

  # POST /accounts
  # POST /accounts.json
  def create
    @account = Account.new(account_params)

    respond_to do |format|
      if @account.save
         @investment = Investment.new(account_id: @account.id)
         @investment.save
        format.html { redirect_to @account, notice: 'account was successfully created.' }
        format.json { render :show, status: :created, location: @account}
      else
        format.html { render :new }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accounts/1
  # PATCH/PUT /accounts/1.json
  def update
    respond_to do |format|
      if @account.update(account_params)
        format.html { redirect_to @account, notice: 'account was successfully updated.' }
        format.json { render :show, status: :ok, location: @account }
      else
        format.html { render :edit }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounts/1
  # DELETE /accounts/1.json
  def destroy
    @account.destroy
    respond_to do |format|
      format.html { redirect_to accounts_url, notice: 'account was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_account
      @account = Account.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def account_params
      params.require(:account).permit(:name, :user_id, :bank, :account_number)
    end

end

app/views/accounts/_form.html.erb
<%= form_with(model: account, local: true) do |form| %>
  <% if account.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(account.errors.count, "error") %> prohibited this account from being saved:</h2>

      <ul>
      <% account.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/accounts/edit.html.erb
<h1>Editing account</h1>

<%= render 'form', account: @account %>

<%= link_to 'Show', @account %> |
<%= link_to 'Back', accounts_path %>

app/views/accounts/index.html.erb
<%= javascript_pack_tag 'hello_react' %>

app/views/accounts/invest.html.erb
<%= javascript_pack_tag 'hello_react' %>

app/views/accounts/show.html.erb
<p id="notice"><%= notice %></p>
<h1>Account</h1>